#' Eliot Dixon, Ashton Drew
#' KDV Decision Analysis LLC
#' Spring 2020

library(sf)
library(urltools)
library(mapview)
library(stringr)
library(mapview)

#' Remove spaces from refuge name prior to writing output files
#' 
#' @param refugeName: char, refuge nam
createNameAbbrev <- function(refugeName){
  dat <- str_replace_all(str_to_title(refugeName), pattern=" ", repl="")
}


#' Check to see if warning indicates result directory couldn't be created
#' 
#' @param warning: warnings generated by call to st_write()
#' TODO: Needs wider use cases to cover other potential warnings/errors
isWriteWarning <- function(warning){
  warningText <- conditionMessage(warning)
  dirWarning <- "cannot create dir"
  return(grepl(dirWarning, warningText, fixed=TRUE))
}


#' Write refuge data to a given location
#' 
#' @param dat: sf, refuge data obtained from FWS Rest API
#' @param refugeName: char, Name of given refuge
#' @param resultsFolder: char, Path to a location in which to store refuge data
#' TODO: Find more direct way to handle generated from call warnings/errors to st_write() 
##' Cleaner way to determine if write was successful
##' Eliminate redundant calls to st_write()
##' Further testing regarding provided file paths
writeFWSCadastral <- function(dat, refugeName, resultsFolder){
  refugeAbbrev <- createNameAbbrev(refugeName)
    #Attempt to write to provided path
    tryCatch({
      if(is.null(resultsFolder)){
        print("Please provide a path to folder in which to store results")
        return()
      }
      else if(!dir.exists(resultsFolder)) {
        dir.create(file.path(resultsFolder))
      }
      st_write(dat, sprintf("%s/%s_ApprovedBoundary.shp",   #Issue *1, this call alwas generates warnings
                            resultsFolder, refugeAbbrev), delete_dsn=TRUE, quiet = TRUE)        
    },
    #Catch warnings, use to determine if output files can be written
    warning = function(w){    #issue *1 Therefor this section will always fire                                                          
      if(isWriteWarning(w)){                                                                   
        print(sprintf("Cannot create/access '%s', please check provided path", resultsFolder)) 
      }
      else{
        st_write(dat, sprintf("%s/%s_ApprovedBoundary.shp", #issue *1 and this call still produces warnings 
                              resultsFolder, refugeAbbrev), delete_dsn=TRUE, quiet = TRUE)
      }
    })
    
}

#' Obtain refuge data from FWS Rest API
#' 
#' @param refugeName: char, Name of desired refuge
#' @param writeResult: boolean, describes whether or not to store obtained data
#' @param resultsFolder: char, path to folder in which to store obtained data
#' TODO: Include check for time out(ie FSW servers are down)
##' Determine how to handle layerName parameter, and how the layers from .gdb relate to variables in data from Rest API
getFWSCadastral <- function(refugeName, writeResult=FALSE, resultsFolder=NULL){
  #generate url to query DB
  baseUrl <- readLines("base_URL.txt")
  url <- param_set(baseUrl, key = "where", value = sprintf("ORGNAME+LIKE+'%s%%25'",gsub(" ","+",refugeName)))
  #query db and read into sf obj
  dat <- read_sf(url)
  if(nrow(dat)==0| is.null(dat)){
    print("No data returned for this data request.  Check the file and layer names.")
  }
  else{
    if(writeResult == TRUE){
      writeFWSCadastral_rough(dat, refugeName,resultsFolder)
    }
    return(dat)
  }
}

dat <- getFWSCadastral("TIJUANA SLOUGH NATIONAL WILDLIFE REFUGE",writeResult = TRUE, resultsFolder = "G:/fake_path")
dat1 <- getFWSCadastral("MERRITT ISLAND NATIONAL WILDLIFE REFUGE")
dat2 <- getFWSCadastral("SANDY POINT NATIONAL WILDLIFE REFUGE", writeResult = TRUE, resultsFolder = "result")















#--------------------------------Spare code below--------------------------------------------------

#old version
getFWSCadastral_old <- function(dataDSN, layerName, refugeName, writeResult=FALSE, resultsFolder=NULL){
  # Get current approved boundary
  dat <- read_sf(dsn=dataDSN, layer=layerName)
  if (nrow(dat)==0| is.null(dat)){
    print("No data returned for this data request.  Check the file and layer names.")
  } else {
    dat <- dplyr::filter(dat, grepl(refugeName, ORGNAME) & RSL_TYPE=="NWR")
    refugeAbbrev <- createNameAbbrev(refugeName)
    
    if (writeResult==TRUE){
      if(is.null(resultsFolder)){
        print("Please provide a path to folder in which to store results")
      }
      else if(!dir.exists(resultsFolder)) {
        dir.create(file.path(resultsFolder))
      }
      st_write(dat, sprintf("%s/%s_ApprovedBoundary.shp", 
                            resultsFolder, refugeAbbrev), delete_dsn=TRUE)
    }
    
    
  }
  return(dat)
}


dsn <- "C:/Users/Eliot/Desktop/Documents/KDV_Decisions/FWS_Proj/Data/GeoDB/FWSCadastral.gdb"
refuge_name <- "TIJUANA SLOUGH NATIONAL WILDLIFE REFUGE" 
layer_name <- "FWSApproved"

cad_data <- getFWSCadastral_old(dsn, layer_name, refuge_name, writeResult = TRUE, resultsFolder = "G:/fake")







writeFWSCadastral_rough <- function(dat, refugeName, resultsFolder){
  refugeAbbrev <- createNameAbbrev(refugeName)
  if(is.null(resultsFolder)){
    print("Please provide a path to folder in which to store results")
    return(dat)
  }
  #if dir exists and has write permission
  else if(dir.exists(resultsFolder)) {
    if(file.access(resultsFolder,2) ==0){
      st_write(dat, sprintf("%s/%s_ApprovedBoundary.shp", 
                            resultsFolder, refugeAbbrev), delete_dsn=TRUE, quiet = TRUE)   
    }
    else{
      print("This program does not have permission to write to that directory")
    }
    #dir.create(file.path(resultsFolder))
  }
  else{
    tryCatch({
      dir.create(file.path(resultsFolder))
    },
    error = function(e){
      #print(e)
      print("unknown error occurred")
      return()
    },
    warning = function(w){
      if(isWriteWarning(w)){                                                                   
        print(sprintf("Cannot create/access '%s', please check provided path", resultsFolder)) 
        stop()
      }
    })
  }
  print("heyyyyyy")
  st_write(dat, sprintf("%s/%s_ApprovedBoundary.shp", 
                        resultsFolder, refugeAbbrev), delete_dsn=TRUE, quiet = TRUE)        
  
}#writeFWSCadastral_Rough







